# Generated by Django 3.2.9 on 2021-11-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='None', max_length=100, verbose_name='author name')),
                ('title', models.CharField(max_length=200, verbose_name='record title')),
                ('text', models.TextField(verbose_name='record text')),
            ],
        ),
    ]
